# Generated by Django 4.0.3 on 2022-04-05 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Working', 'Working'), ('Done', 'Done')], default='Waiting', max_length=50)),
                ('control_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('map', models.TextField(blank=True, null=True)),
                ('project_address', models.TextField()),
            ],
            options={
                'db_table': 'Project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('robot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('robot_name', models.CharField(max_length=50)),
                ('robot_status', models.CharField(choices=[('Available', 'Available'), ('Working', 'Working'), ('At Maintainance', 'At Maintainance')], default='Available', max_length=50)),
                ('robot_image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Robot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('project_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('x_position', models.DecimalField(decimal_places=5, max_digits=10)),
                ('y_position', models.DecimalField(decimal_places=5, max_digits=10)),
                ('angle', models.DecimalField(decimal_places=5, max_digits=10)),
                ('speed', models.DecimalField(decimal_places=5, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=5, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=5, max_digits=10)),
                ('gas_type', models.CharField(blank=True, max_length=100, null=True)),
                ('gas_reading', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('control_type', models.CharField(max_length=50)),
                ('time_collected', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maps.project')),
            ],
            options={
                'db_table': 'Project_Data',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maps.robot'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CameraFrame',
            fields=[
                ('camera_frame_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frame', models.BinaryField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maps.project')),
            ],
            options={
                'db_table': 'Camera_Frame',
                'managed': True,
            },
        ),
    ]
