# Generated by Django 4.0.3 on 2022-05-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_project_created_alter_project_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='x',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
