# Generated by Django 4.0.3 on 2022-04-05 13:54

from django.db import migrations, models
import maps.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=maps.models.user_directory_path),
        ),
    ]
