# Generated by Django 4.0.3 on 2022-05-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_project_created_alter_project_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
