# Generated by Django 4.0.3 on 2022-04-28 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_robot_robot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='control_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Working', 'Working'), ('Done', 'Done')], default='Waiting', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='robot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='maps.robot'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
