# Generated by Django 4.0.3 on 2022-04-28 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maps.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_project_control_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=maps.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='robot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='maps.robot'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
