# Generated by Django 4.0.3 on 2022-04-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_alter_robot_robot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='control_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.project'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
