# Generated by Django 4.0.3 on 2022-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_alter_projectdata_time_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='time_collected',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
