# Generated by Django 4.0.3 on 2022-05-27 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maps.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_alter_projectdata_time_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to=maps.models.map_directory_path),
        ),
    ]
