# Generated by Django 4.0.3 on 2022-04-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_alter_project_robot_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='robot_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='robot_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Working', 'Working'), ('At Maintainance', 'At Maintainance')], default='Available', max_length=20),
        ),
    ]
