# Generated by Django 4.0.3 on 2022-04-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_alter_robot_robot_name_alter_robot_robot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
