# Generated by Django 4.0.3 on 2022-04-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=20),
        ),
    ]
