# Generated by Django 4.0.3 on 2022-05-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_alter_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='at_maintainance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='robot',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
