# Generated by Django 4.0.3 on 2022-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_robot_at_maintainance_robot_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='robot_status',
        ),
        migrations.AddField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
