# Generated by Django 4.0.3 on 2022-05-04 22:21

from django.db import migrations, models
import maps.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_remove_project_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to=maps.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='robot',
            name='robot_image',
            field=models.ImageField(blank=True, default='default_robot.png', null=True, upload_to=maps.models.robot_directory_path),
        ),
    ]
